import { useEffect, useMemo, useRef, useState } from "react";
import type { AccountDraft, Draft, PlanResponse, ProjectionResponse } from "./model.js";
import { ApiFailure, api, blankAccount, initialDraft, money, toInput } from "./model.js";

const TYPES = [["traditional_ira", "Traditional IRA"], ["roth_ira", "Roth IRA"], ["brokerage", "Brokerage"], ["employer401k", "Employer 401(k)"], ["cash", "Cash"], ["other", "Other"]] as const;
export function App(): React.JSX.Element {
  const [draft, setDraft] = useState<Draft>(initialDraft); const [saved, setSaved] = useState<PlanResponse>(); const [projection, setProjection] = useState<ProjectionResponse>();
  const [notice, setNotice] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [degraded, setDegraded] = useState(false); const [recovery, setRecovery] = useState<"stale" | "missing" | "restart">();
  const instance = useRef<string | undefined>(undefined);
  useEffect(() => { void Promise.allSettled([api.ready(), api.live()]).then(([ready, live]) => { setDegraded(ready.status === "rejected"); if (live.status === "fulfilled") { const prior = sessionStorage.getItem("retirement.instance"); instance.current = live.value.instance_id; sessionStorage.setItem("retirement.instance", live.value.instance_id); if (prior !== null && prior !== live.value.instance_id) setRecovery("restart"); } }); }, []);
  const fields = useMemo(() => { const result: Record<string, string> = {}; for (const [path, message] of Object.entries(errors)) result[path] = message; return result; }, [errors]);
  const editProfile = (key: keyof Draft["profile"], value: string) => setDraft((current) => ({ ...current, profile: { ...current.profile, [key]: value } }));
  const editAccount = <K extends keyof AccountDraft>(index: number, key: K, value: AccountDraft[K]) => setDraft((current) => ({ ...current, accounts: current.accounts.map((account, position) => position === index ? { ...account, [key]: value } : account) }));
  const checkInstance = async () => { const live = await api.live(); if (instance.current !== undefined && instance.current !== live.instance_id) { setRecovery("restart"); setSaved(undefined); } instance.current = live.instance_id; sessionStorage.setItem("retirement.instance", live.instance_id); };
  const perform = async (work: () => Promise<void>) => { setBusy(true); setErrors({}); try { await checkInstance(); await work(); } catch (error) { if (error instanceof ApiFailure) { setErrors(Object.fromEntries(error.response.field_errors.map((item) => [item.path, item.message]))); setNotice(`${error.response.message}${error.response.request_id ? ` Request ID: ${error.response.request_id}` : ""}`); } else setNotice(error instanceof Error ? error.message : "Unexpected error"); } finally { setBusy(false); } };
  const save = () => perform(async () => { try { const input = toInput(draft); const result = saved === undefined ? await api.create(input) : await api.update(saved, input); setSaved(result); setRecovery(undefined); setNotice("Plan saved in this local service session."); } catch (error) { if (error instanceof ApiFailure && error.response.code === "REVISION_CONFLICT") { setRecovery("stale"); setNotice("A newer saved version exists"); return; } if (error instanceof ApiFailure && error.response.code === "PLAN_NOT_FOUND") { setRecovery("missing"); setNotice("Saved plan is missing"); return; } throw error; } });
  const project = () => perform(async () => { const result = await api.project(toInput(draft)); setProjection(result); setNotice(""); });
  const replace = () => perform(async () => { const result = await api.create(toInput(draft)); setSaved(result); setRecovery(undefined); setNotice("Plan saved in this local service session."); });
  const retryStale = () => perform(async () => { if (saved === undefined) return; const latest = await api.get(saved.plan_id); const result = await api.update(latest, toInput(draft)); setSaved(result); setRecovery(undefined); setNotice("Plan saved in this local service session."); });
  return <><a className="skip-link" href="#planner">Skip to planner</a><header className="site-header"><div className="brand"><span className="brand-mark">R</span><div><strong>Retirement Planner</strong><span>Transparent, year-by-year projections</span></div></div><span className="trust-badge">Your data stays in this session</span></header>
    <main><section className="hero"><div><span className="eyebrow">Plan with clarity</span><h1>Build a retirement scenario you can inspect.</h1><p>Model your accounts, contributions, growth, and income using a transparent annual projection.</p></div><aside><strong>No hidden assumptions</strong><p>Every balance and dividend is visible in the accessible results table.</p></aside></section>
    <div className="planner-grid" id="planner"><div className="editor"><section className="panel"><span className="eyebrow">Your profile</span><h2>Projection basics</h2><div className="field-grid profile-grid"><Field id="current-age" label="Current age" value={draft.profile.age} onChange={(value) => editProfile("age", value)} error={fields["profile.current_age"]}/><Field id="annual-income" label="Annual income" value={draft.profile.income} onChange={(value) => editProfile("income", value)} error={fields["profile.current_annual_income_cents"]}/><Field id="projection-years" label="Projection years" value={draft.profile.years} onChange={(value) => editProfile("years", value)} error={fields["profile.projection_years"]}/></div></section>
    <section className="accounts-section"><div className="section-heading"><div><span className="eyebrow">Accounts</span><h2>Where your money lives</h2></div><button className="button-secondary" onClick={() => setDraft((current) => ({ ...current, accounts: [...current.accounts, blankAccount()] }))}>+ Add account</button></div>
    {draft.accounts.length === 0 ? <div className="empty-state"><h3>No accounts yet</h3><button onClick={() => setDraft((current) => ({ ...current, accounts: [blankAccount()] }))}>Add your first account</button></div> : draft.accounts.map((account, index) => <AccountCard key={account.id} account={account} index={index} edit={editAccount} duplicate={() => setDraft((current) => ({ ...current, accounts: [...current.accounts.slice(0, index + 1), { ...account, id: crypto.randomUUID(), name: `${account.name} copy` }, ...current.accounts.slice(index + 1)] }))} remove={() => setDraft((current) => ({ ...current, accounts: current.accounts.filter((_, position) => position !== index) }))}/>)}</section>
    {notice && <div className="notice" role="status">{notice}</div>}{recovery && <div className="banner"><strong>{recovery === "restart" ? "Service memory was reset" : recovery === "stale" ? "A newer saved version exists" : "Saved plan is missing"}</strong><span>Your draft is preserved.</span><div>{recovery === "stale" && <button onClick={retryStale}>Reapply my changes</button>}{recovery !== "stale" && <button onClick={replace}>Create replacement</button>}</div></div>}
    {projection && <Results projection={projection}/>}</div>
    <aside className="action-rail"><div className="action-card"><span className="eyebrow">Ready when you are</span><h2>Run your scenario</h2><p>Project without saving, or keep a revision in this service session.</p><button disabled={busy} className="button-primary button-full" onClick={project}>Project retirement</button><button id="save-button" disabled={busy || degraded} className="button-secondary button-full" onClick={save}>{saved === undefined ? "Save plan" : "Save changes"}</button>{saved && <button disabled={busy} className="button-danger button-full" onClick={() => perform(async () => { await api.remove(saved.plan_id); setSaved(undefined); setNotice("Saved plan deleted. Your draft is preserved."); })}>Delete saved plan</button>}<small>{degraded ? "Saving temporarily unavailable" : "Saved plans reset when the service restarts."}</small></div></aside></div></main><footer>Educational projections only — not financial advice.</footer></>;
}

function Field({ id, label, value, onChange, error }: { id: string; label: string; value: string; onChange: (value: string) => void; error?: string | undefined }): React.JSX.Element { return <div className="field"><label htmlFor={id}>{label}</label><input id={id} value={value} aria-invalid={error ? true : undefined} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value)}/>{error && <p className="field-error" id={`${id}-error`}>{error}</p>}</div>; }
function AccountCard({ account, index, edit, duplicate, remove }: { account: AccountDraft; index: number; edit: <K extends keyof AccountDraft>(index: number, key: K, value: AccountDraft[K]) => void; duplicate: () => void; remove: () => void }): React.JSX.Element { const prefix = `account-${String(index)}`; return <article className="account-card" data-account-index={index}><div className="account-heading"><h3>Account {index + 1}</h3><div className="account-actions"><button className="button-quiet" onClick={duplicate}>Duplicate</button><button className="button-danger" aria-label={`Remove account ${String(index + 1)}`} onClick={remove}>Remove</button></div></div><div className="field-grid"><Field id={`${prefix}-name`} label="Account name" value={account.name} onChange={(value) => edit(index, "name", value)}/><div className="field"><label htmlFor={`${prefix}-type`}>Account type</label><select id={`${prefix}-type`} value={account.type} onChange={(event) => edit(index, "type", event.target.value as AccountDraft["type"])}>{TYPES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{account.type === "other" && <Field id={`${prefix}-other`} label="Other account type" value={account.other} onChange={(value) => edit(index, "other", value)}/>}<Field id={`${prefix}-balance`} label="Starting balance" value={account.balance} onChange={(value) => edit(index, "balance", value)}/><Field id={`${prefix}-basis`} label="Cost basis" value={account.basis} onChange={(value) => edit(index, "basis", value)}/><Field id={`${prefix}-growth`} label="Annual growth (%)" value={account.growth} onChange={(value) => edit(index, "growth", value)}/><Field id={`${prefix}-yield`} label="Dividend yield (%)" value={account.dividend} onChange={(value) => edit(index, "dividend", value)}/><Field id={`${prefix}-allocation`} label="Income contribution (%)" value={account.allocation} onChange={(value) => edit(index, "allocation", value)}/><label className="toggle"><input type="checkbox" checked={account.reinvest} onChange={(event) => edit(index, "reinvest", event.target.checked)}/>Reinvest dividends</label></div></article>; }
function Results({ projection }: { projection: ProjectionResponse }): React.JSX.Element { const last = projection.years.at(-1)?.portfolio; const chartFailed = new URLSearchParams(location.search).get("chart") === "fail"; return <section className="results" aria-live="polite"><span className="eyebrow">Projection complete</span><h2>Your outlook</h2><div className="result-cards">{[["Ending balance", last?.closing_balance_cents ?? 0n], ["Total contributions", projection.years.reduce((sum, row) => sum + row.portfolio.contribution_cents, 0n)], ["Annual income paid", last?.income_paid_cents ?? 0n], ["Cumulative income", last?.cumulative_income_paid_cents ?? 0n]].map(([label, value]) => <div className="result-card" key={String(label)}><span>{String(label)}</span><strong>{money(value as bigint)}</strong></div>)}</div><div className="chart-panel">{chartFailed ? <div className="chart-fallback"><strong>Chart unavailable</strong><span>The complete data remains available below.</span></div> : <svg className="chart" role="img" aria-label="Projected closing balance chart" viewBox="0 0 1000 220" preserveAspectRatio="none"><polyline fill="none" points={projection.years.map((row, index) => `${String((index / Math.max(1, projection.years.length - 1)) * 1000)},${String(210 - Number(row.portfolio.closing_balance_cents) / Math.max(1, ...projection.years.map((entry) => Number(entry.portfolio.closing_balance_cents))) * 200)}`).join(" ")}/></svg>}</div><div className="table-scroll"><table><caption>Annual portfolio projection</caption><thead><tr><th>Year / age</th><th>Opening</th><th>Contribution</th><th>Growth</th><th>Income</th><th>Closing</th></tr></thead><tbody>{projection.years.map((row) => <tr key={row.year}><th>{row.year} / {row.age}</th><td>{money(row.portfolio.opening_balance_cents)}</td><td>{money(row.portfolio.contribution_cents)}</td><td>{money(row.portfolio.appreciation_cents)}</td><td>{money(row.portfolio.income_paid_cents)}</td><td>{money(row.portfolio.closing_balance_cents)}</td></tr>)}</tbody></table></div></section>; }
